require:
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.3
  Include:
    - lib/*.rb
    - lib/**/*.rb
    - test/*_test.rb

##
# Enabled
Style/FrozenStringLiteralComment:
  Enabled: true

##
# Disabled
