require:
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.3
  Include:
    - lib/*.rb
    - lib/**/*.rb
    - test/*_test.rb

##
# Enabled
Style/FrozenStringLiteralComment:
  Enabled: true

##
# Disabled
Style/MultilineIfModifier:
  Enabled: false
Layout/ArrayAlignment:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: False
Layout/MultilineArrayBraceLayout:
  Enabled: false
Layout/MultilineArrayBraceLayout:
  Enabled: false
Layout/ExtraSpacing:
  Exclude:
    - lib/bsd/capsicum/constants.rb
